# How to use Python for Linear Algebra


### 5 usefull functions


- arange
- reshape
- random
- descriptive analysis (min, max, mean, std)
- Matrix multiplication (and simpler algebra)

In [1]:
!pip install jovian --upgrade -q

You should consider upgrading via the '/opt/conda/bin/python3.7 -m pip install --upgrade pip' command.


In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
jovian.commit(project='z2p-02-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Uploading notebook to https://jovian.ml/anivorlis/z2p-02-numpy-array-operations


<IPython.core.display.Javascript object>

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.arange
function2 = np.linspace
function3 = np.random # np.reshape
function4 = np.min #np.max, np.mean
function5 = np.dot

## Function 1 - np.arange

This function creates a new 1d-array (vector) with a given range
np.arange(start, end, step)

In [6]:
# Example 1 - working
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

If only one number is given then the function has starting=0 and step=1, similar to python's native range generator

In [8]:
# Example 2 - working
arr = np.arange(10, 20, 2)
arr

array([10, 12, 14, 16, 18])

In this example we start from 10 and increase with a step of 2 until but not including 20.

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.arange([1,5,1])
arr

TypeError: unsupported operand type(s) for -: 'list' and 'int'

Some numpy function accept a list of numbers (usually the dimensions). np.arange accepts integers (1, 2 or 3) and not a list of integers.

This function is very usefull when we want to generate an array with known limits and spacing.

In [16]:
jovian.commit(project='z2p-02-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/anivorlis/z2p-02-numpy-array-operations


<IPython.core.display.Javascript object>

## Function 2 - np.linspace

This function creates a new 1d-array (vector) with a given range by specifying the number of points in between.
np.linspace(start, end, num=50)

In [18]:
# Example 1 - working
arr = np.linspace(5, 8)
arr

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

We generate an array with 50 points starting from 5 to 8

In [19]:
# Example 2 - working
arr = np.linspace(5, 8, 10)
arr

array([5.        , 5.33333333, 5.66666667, 6.        , 6.33333333,
       6.66666667, 7.        , 7.33333333, 7.66666667, 8.        ])

We generate an array with 10 points starting from 5 to 8.

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.linspace(5)
arr

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

With np.linspace we must specify a starting point and an ending point.

Another way to generate an array is to know the limits but instead of specifying the space, we would like to specify the number of points in between. With np.linspace the start/end points are always included in the results. The number of points in between is equal to num-2, where num is the input to the function.

In [21]:
jovian.commit(project='z2p-02-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/anivorlis/z2p-02-numpy-array-operations


<IPython.core.display.Javascript object>

## Function 3 - np.random

Sometimes we just want a random array to test things. Random numbers are uniform distributed between [0,1)


In [29]:
# Example 1 - working
arr = np.random.random([5])
arr

array([0.38821369, 0.21605037, 0.0028763 , 0.45804913, 0.90452791])

5 random numbers in a 1d array (vector)

In [30]:
# Example 2 - working
arr = np.random.random([5, 2])
arr

array([[0.61235908, 0.10386897],
       [0.25008058, 0.30838794],
       [0.41373447, 0.01292821],
       [0.34253927, 0.1960847 ],
       [0.03129582, 0.731084  ]])

Random 2d vector with shape 5x2

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.random.random([5.1, 2.2])
arr

TypeError: 'float' object cannot be interpreted as an integer

The input must be integers that describe the dimensions of the vector. If it's a variable cast it to int.

Random numbers are a usefull way to generate vector when testing stuff.

In [32]:
jovian.commit(project='z2p-02-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/anivorlis/z2p-02-numpy-array-operations


<IPython.core.display.Javascript object>

## Function 4 - np.min, np.max, np.mean, np.std

Functions for descriptive analysis of a vector or matrix

In [37]:
# Example 1 - working
arr = np.random.random([1000]) 
np.min(arr), np.max(arr)

(0.0013547899896226845, 0.9988486065942548)

Get the minimum and the maximum of the array. The values make sense since the np.random.random generates random numbers between [0,1)

In [38]:
# Example 2 - working
arr = np.random.random([1000]) 
np.mean(arr), np.std(arr)

(0.4973558685802408, 0.28438406395259763)

Furthermore, we can explore the mean and standar deviation (std) of the arr. Since it is a uniform distribution the mean is 0.5 and the std 0.28 which makes sense. 

In [42]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array(['a', 'b', 'c'])
arr
np.min(arr)

TypeError: cannot perform reduce with flexible type

numpy arrays can contain more than just numbers (for example strings). Before using a function make sure that the array has numeric values stored.

Very usefull functions for statistical analysis of arrays and matrices.

In [43]:
jovian.commit(project='z2p-02-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/anivorlis/z2p-02-numpy-array-operations


<IPython.core.display.Javascript object>

## Function 5 - np.dot

Calculates the dot product between two vectors, a vector and a matrix or two matrices.

In [46]:
# Example 1 - working
arr1 = np.array([2,2,2])
arr2 = np.array([2,2,2])
arr = np.dot(arr1, arr2)
arr

12

Inner dot product of two vectors is a number

In [51]:
# Example 2 - working
arr1 = np.array([ [2, 2], [2,2] ])
arr2 = np.array([ [2, 2], [2,2] ])
arr = np.dot(arr1, arr2)
arr

array([[8, 8],
       [8, 8]])

Matrix multiplication between two matrices.

In [52]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([2,2,2])
arr2 = np.array([2,2,2, 2])
arr = np.dot(arr1, arr2)
arr

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

You need to make sure that the dimensions are suitable for the operation.

The function is usefull when you are using numpy to solve linear algebra systems. From simple equations all the way to machine learning.

In [53]:
jovian.commit(project='z2p-02-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/anivorlis/z2p-02-numpy-array-operations


<IPython.core.display.Javascript object>

## Conclusion

This notebook covers some basic functions in the numpy library. First, we look for functions that are used to generate arrays (np.arange, np.linspace and np.random.random). Then we look at some functions for descriptive statistics (np.min, np.max, np.mean, np.std) to analyse a vector or matrix. Last, we look at a function for doing vector/matrix multiplication (np.dot). Overall, numpy is a complete library for doing linear algebra and often is paired with scipy (scientific python) to solve more complex problems. 

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Scipy official page: https://www.scipy.org/

In [54]:
jovian.commit(project='z2p-02-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/anivorlis/z2p-02-numpy-array-operations


<IPython.core.display.Javascript object>