# Assignment 1

### Getting familiar with pyTorch

An short introduction about PyTorch and about the chosen functions. 
- tensor() and from_numpy()
- rand() and randn()
- l1_loss() and mse_loss()
- where()
- linspace() and logspace()

In [3]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.tensor() and torch.from_numpy()

Tensor is the fundamental data structure of torch. Tensors are basically multidimension matrices

In [2]:
# Example 1 - create a simple tensor [2x3]
data = torch.tensor( [[1, 2, 3], 
                      [4, 5, 6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

Create a tensor by hard-coding the values

In [3]:
# Create a [2x3] tensor from a numpy n-dimension array
input = np.array( [[1, 2, 3],
                   [4, 5, 6]])
data = torch.from_numpy(input)
data

tensor([[1, 2, 3],
        [4, 5, 6]])

Create a tensor from a numpy array. OBS! They share memory.

In [4]:
# Example 3 - data type must match
data = torch.tensor([[1, 2], 
                     [3, '4']])
data

TypeError: new(): invalid data type 'str'

The values in the sensor must be of the same type. 

Tensor are the basic data structure of pyTorch. It is essential to know how to initialize them and populate them with data.

## Function 2 - torch.rand() and torch.randn()

Initialize a tensor with random numbers. Examples with random and uniform distributed.

In [5]:
N = 30_000
data = torch.rand( [N])
print('mean of: ', data.mean())
print('std of: ', data.std())
print('[', data.min(), ', ', data.max(), ']')

mean of:  tensor(0.4996)
std of:  tensor(0.2900)
[ tensor(3.7730e-05) ,  tensor(1.0000) ]


Random numbers generated with a normal distribution with a center of 0

In [6]:
N = 30_000
data = torch.randn( [N])
print('mean of: ', data.mean())
print('std of: ', data.std())
print('[', data.min(), ', ', data.max(), ']')

mean of:  tensor(-0.0028)
std of:  tensor(1.0020)
[ tensor(-4.0740) ,  tensor(4.2448) ]


Random numbers generated with a uniform distribution between the interval [0, 1]

In [7]:
N = 30_000
lower_bound = -10
upper_bound = 20
data = torch.rand( [N])
data = (upper_bound - lower_bound) * data + lower_bound
print('mean of: ', data.mean())
print('std of: ', data.std())
print('[', data.min(), ', ', data.max(), ']')

mean of:  tensor(5.0029)
std of:  tensor(8.6449)
[ tensor(-9.9977) ,  tensor(19.9996) ]


Random numbers generated with a uniform distribution between the interval [-10, 20]

In [8]:
values = np.array ( [0, 0, 0, 'a', 0, 0])
print(values)
data = torch.from_numpy(values)
data

['0' '0' '0' 'a' '0' '0']


TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

In numpy you can have different dtypes in the array but not in tensor so it will break

Very often you need to populate a tensor with random numbers. That could be for an initial solution or for the weights. It is important to know the properties of the distribution of the random numbers.

## Function 3 - Loss functions

Identify different loss functions

In [1]:
import torch.nn.functional as F

In [4]:
target = torch.Tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
prediction = torch.Tensor([4.5, 4.6, 4.7, 4.8, 4.9, 5.1, 5.2, 5.3, 5.4, 5.5])
loss1 = F.l1_loss(target, prediction)
print(loss1)
loss2 = np.sqrt(F.mse_loss(target, prediction))
print(loss2)

tensor(0.3000)
tensor(0.3317)


The RMSE and the l1_loss are very similar when there are not extreme values in the prediction.

In [5]:
target = torch.Tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
prediction = torch.Tensor([4.5, 4.6, 4.7, 4.8, 4.9, 5.1, 5.2, 5.3, 5.4, 5.5, 1000])
loss1 = F.l1_loss(target, prediction)
print(loss1)
loss2 = np.sqrt(F.mse_loss(target, prediction))
print(loss2)

tensor(90.7273)
tensor(300.0040)


The RMSE and the l1_loss are different when there **ARE** extreme values in the prediction. More specifically, the RMSE is much higher when extreme values are present in the prediction. 

In [12]:
target = torch.Tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
prediction = torch.Tensor([4.5, 4.6, 4.7, 4.8, 4.9, 5.1, 5.2, 5.3, 5.4, 5.5, 1000])
loss1 = F.l1_loss(torch.sigmoid(target), prediction)
print(loss1)
loss2 = np.sqrt(F.mse_loss(torch.sigmoid(target), prediction))
print(loss2)

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Using a target size (torch.Size([11])) that is different to the input size (torch.Size([12])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  This is separate from the ipykernel package so we can avoid doing imports until


RuntimeError: The size of tensor a (12) must match the size of tensor b (11) at non-singleton dimension 0

The code will break if the target and the prediction have different size

The essence of ML is to minimize a loss function hence match the predictions as close as possible to the target values. It is important to use a loss function that makes more sense based on your data and the model that you want to train.

## Function 4 - torch.where()

Filter the input based on a statement

In [14]:
data = torch.Tensor( [[4.5, 5, -1.5, 4],
                      [3, 2, -1.5, 3],
                      [1.5, 8, -3, 4]])
data_correct = torch.where(data > 0, data, data.abs())
print(data_correct)

tensor([[4.5000, 5.0000, 1.5000, 4.0000],
        [3.0000, 2.0000, 1.5000, 3.0000],
        [1.5000, 8.0000, 3.0000, 4.0000]])


Tensor has depth information. Sometimes they can be negative so we would always like to get data as positivie values.

In [15]:
data1 = torch.Tensor([[5, 3 ,10, 0],
                      [6, 7, 15, 1]])
data2 = torch.Tensor([[5, 3 ,10, 7],
                      [6, 7, 15, 1]])
data = torch.where(data1 !=0, data1, data2)
data

tensor([[ 5.,  3., 10.,  7.],
        [ 6.,  7., 15.,  1.]])

Data1 contains the data from a weather station for specific days. Data2 contains the data from another weather station for the same time period. Sometimes a weather station will have missing data marked with zero. We can combine the data in one final data tensor with the where() function.

In [16]:
data1 = torch.Tensor([[5, 3 ,10, 0],
                      [6, 7, 15, 1]])
data2 = torch.Tensor([[5, 3 ,10, 7],
                      [6, 7, 15, 1, 1]])
data = torch.where(data1 !=0, data1, data2)
data

ValueError: expected sequence of length 4 at dim 1 (got 5)

The code will break if data1 and data2 are not the same size.

where() is a very important function to filter the input data based on some criterion.

## Function 5 - linspace() and logspace()

Create a 1D tensor with N values spaced equaly in linear and/or logarithmic space.

In [17]:
N = 10
starting_value = 1
ending_value = 2
data = torch.linspace(starting_value, ending_value, N)
data

tensor([1.0000, 1.1111, 1.2222, 1.3333, 1.4444, 1.5556, 1.6667, 1.7778, 1.8889,
        2.0000])

Create N points in the interval [1, 2]. The points have equal distance in the linear scale. OBS! Starting and ending value will always be included.

In [18]:
N = 10
starting_value = 2
ending_value = 3
base = 3
data = torch.logspace(starting_value, ending_value, N, base)
data

tensor([ 9.0000, 10.1685, 11.4887, 12.9802, 14.6655, 16.5695, 18.7208, 21.1513,
        23.8974, 27.0000])

Create N points in the interval [3^2, 3^3]. The points have equal distance in the logarithmic scale. OBS! Starting and ending value will always be included.

In [19]:
N = 10.5
starting_value = 2
ending_value = 3
data = torch.linspace(starting_value, ending_value, N)
data

TypeError: linspace(): argument 'steps' (position 3) must be int, not float

The function will break if the N is not an integer. That can be a common mistake when N is a variable that is acquired for a division for example, so it is always good to round it up to the nearest integer.

The function is very useful when we want to generate N points over a specific range. It can for example be a good way of generating a random input for a stohastic random model.

## Conclusion

There are a lot of similarities between the numpy and tensor methods, which is a very positive thing about pyTorch. It was nice reading through the docs and getting some insights about the basic data structures and the tools available to help me start building my models.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [8]:
!pip install jovian --upgrade --quiet

In [6]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
